#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Unified build script for Fink Docker images

set -euo pipefail

DIR=$(cd "$(dirname "$0")"; pwd -P)

usage() {
  cat << EOD

Usage: $(basename "$0") [options]

  Available options:
    -h                  this message
    -t TARGET           target to build: k8s, sentinel
    --noscience         build noscience image (k8s only, default: science)
    -i SURVEY           survey: ztf, rubin (default: ztf)
    --verbose           verbose build output

Build Fink Docker images:
  - k8s: Build Kubernetes image using Dockerfile.k8s
  - sentinel: Build sentinel development image (specify survey with -i)

Examples:
  $(basename "$0") -t k8s --noscience -i ztf        # K8s noscience image for ZTF
  $(basename "$0") -t k8s -i rubin                  # K8s science image for Rubin
  $(basename "$0") -t sentinel -i rubin             # Sentinel Rubin image
  $(basename "$0") -t sentinel -i ztf               # Sentinel ZTF image

EOD
}

# Default values
TARGET=""
NOSCIENCE=false
SURVEY="ztf"
VERBOSE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;
        -t|--target)
            TARGET="$2"
            shift 2
            ;;
        --noscience)
            NOSCIENCE=true
            shift
            ;;
        -i|--survey)
            SURVEY="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Validate target
if [[ -z "$TARGET" ]]; then
    echo "Error: Target (-t) is required"
    usage
    exit 1
fi

if [[ ! "$TARGET" =~ ^(k8s|sentinel)$ ]]; then
    echo "Error: Invalid target '$TARGET'. Must be: k8s or sentinel"
    exit 1
fi

# Validate survey for all builds
if [[ ! "$SURVEY" =~ ^(ztf|rubin)$ ]]; then
    echo "Error: Invalid survey '$SURVEY'. Must be: ztf or rubin"
    exit 1
fi

# Validate that noscience is only used with k8s target
if [[ "$TARGET" == "sentinel" && "$NOSCIENCE" == true ]]; then
    echo "Error: --noscience option is only supported for k8s builds"
    exit 1
fi

# Note: Tag is generated by ciux for sentinel builds

# Set verbose options
EXTRA_ARGS=""
if [[ "$VERBOSE" == true ]]; then
    EXTRA_ARGS="--progress=plain"
fi

# Build functions
build_k8s() {
    # Determine suffix based on noscience flag
    if [[ "$NOSCIENCE" == true ]]; then
        SUFFIX="noscience"
        docker_target="noscience"
    else
        SUFFIX="science"
        docker_target="science"
    fi

    echo "Building K8s image for $SURVEY survey with $SUFFIX target"

    # This command avoids building if not needed
    SUFFIX="$SUFFIX-$SURVEY"
    $(ciux get image --check "$DIR" --suffix "$SUFFIX" --env)

    if [ "$CIUX_BUILD" = false ]; then
        echo "Build cancelled, image $CIUX_IMAGE_URL already exists and contains current source code"
        exit 0
    fi

    ciux ignite --selector build,k8s "$DIR" --suffix "$SUFFIX"
    . $DIR/.ciux.d/ciux_build-k8s.sh

    # Build K8s image
    docker image build $EXTRA_ARGS \
        --tag "$CIUX_IMAGE_URL" \
        --build-arg spark_py_image="$ASTROLABSOFTWARE_FINK_SPARK_PY_IMAGE" \
        --build-arg input_survey="$SURVEY" \
        --file "$DIR/Dockerfile.k8s" \
        --target "$docker_target" \
        "$DIR"

    echo "Build successful: $CIUX_IMAGE_URL"
}

build_sentinel() {
    echo "Building sentinel development image for $SURVEY survey"

    SUFFIX="sentinel-$SURVEY"
    # This command avoid building if not needed
    $(ciux get image --check "$DIR" --suffix "$SUFFIX" --env)

    if [ "$CIUX_BUILD" = false ]; then
        echo "Build cancelled, image $CIUX_IMAGE_URL already exists and contains current source code"
        exit 0
    fi

    echo "Building $SURVEY sentinel image with tag: $CIUX_IMAGE_URL"
    echo "Versions will be sourced from ${SURVEY}/versions.sentinel.sh inside the Docker build"

    docker build $EXTRA_ARGS \
        --tag "$CIUX_IMAGE_URL" \
        -f "$DIR/Dockerfile.sentinel" \
        --build-arg input_survey="$SURVEY" \
        .

    echo "Build successful: $CIUX_IMAGE_URL"
}

# Main execution
case "$TARGET" in
    k8s)
        build_k8s
        ;;
    sentinel)
        build_sentinel
        ;;
esac
