#!/bin/bash
# Copyright 2022 AstroLab Software
# Author: Julien Peloton
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e
message_help="""
Build Dockerfile image for Fink\n\n
Usage:\n
    ./fink_docker [-h] \n
    ./fink_docker --build [--os] [--tag] [--verbose] [--astronet-token] \n
    ./fink_docker --run [--tag] \n\n

Specify the name of a folder with a Dockerfile with the option --os.\n
Use --build to build the image from the Dockerfile in --os, with a tag (--tag).\n
Use --run with a tag (--tag) to enter the container instead\n
For the deployment, you need to have credentials defined.\n
Use -h to display this help.
"""

# Show help if no arguments is given
if [[ $1 == "" ]]; then
  echo -e $message_help
  exit 1
fi

# Grab the command line arguments
BUILD=false
RUN=false
DEPLOY=false
VERBOSE=false
ASTRONETTOKEN=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -h)
        echo -e $message_help
        exit
        ;;
    --os)
        if [[ $2 == "" ]]; then
          echo "$1 requires an argument" >&2
          exit 1
        fi
        OS_NAME="$2"
        shift 2
        ;;
    --tag)
        if [[ $2 == "" ]]; then
          echo "$1 requires an argument" >&2
          exit 1
        fi
        TAG="$2"
        shift 2
        ;;
    --build)
        BUILD=true
        shift 1
        ;;
    --run)
        RUN=true
        shift 1
        ;;
    --deploy)
        DEPLOY=true
        shift 1
        ;;
    --astronet-token)
        ASTRONETTOKEN="$2"
        shift 2
        ;;
    --verbose)
        VERBOSE=true
        shift 1
        ;;
  esac
done

if [[ $BUILD == true ]]; then
  if [[ $OS_NAME == "" ]]; then
    echo "You need to specify the name of a folder with a Dockerfile with the option --os."
    exit
  fi
  if [[ $TAG == "" ]]; then
    echo "You need to specify the tag with the option --tag."
    echo `docker build --help | grep "tag list"`
    exit
  fi
  EXTRA_ARGS=""
  if [[ $VERBOSE == true ]]; then
    EXTRA_ARGS="--progress=plain"
  fi
  BUILD_ARGS=""
  if [[ $ASTRONETTOKEN != "" ]]; then
      BUILD_ARGS="--build-arg ASTRONETTOKEN=$ASTRONETTOKEN"
  fi
  echo "Building ${OS_NAME}"
  docker build $EXTRA_ARGS $BUILD_ARGS -f ${OS_NAME}/Dockerfile -t ${TAG} .
elif [[ $RUN == true ]]; then
  if [[ $TAG == "" ]]; then
    echo "You need to specify the image name with the option --tag."
    exit
  fi
  docker run -t -i --rm ${TAG} bash
fi
